name: QA

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [16, 18, 20]
        workdir: [client, generator]

    defaults:
      run:
        working-directory: ${{ matrix.workdir }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: npm
      - run: npm ci --prefer-offline
      - run: npm run lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [16, 18, 20]
        workdir: [client, generator]

    defaults:
      run:
        working-directory: ${{ matrix.workdir }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: npm
      - run: npm ci --prefer-offline
      - run: npm run test:coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
